### ISSUE TITLE
Proxy settings in Windows

### ISSUE THREAD

**Issue by jeroenooms** [jeroenooms/curl#1]
Read proxy settings in windows to mimic `setInternet2`:

http://stackoverflow.com/questions/202547/how-do-i-find-out-the-browsers-proxy-settings

**Comment by hadley** [comment]
Oh that would be awesome!

**Comment by jeroenooms** [comment]
I've implemented a function `ie_proxy_info` that looks up this information on windows. Thereby users or high level packages can decide for themselves if they want to use this to automatically set `CURLOPT_PROXY`.

**Comment by hadley** [comment]
What's the argument for not doing this by default?

**Comment by jeroenooms** [comment]
It's windows, it has it's own logic/configuration that might not map perfectly to libcurl. But maybe if we test it and it works well can do it by default.

**Comment by jeroenooms** [comment]
So the [API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384250(v=vs.85).aspx) returns these 4 fields:

 - `fAutoDetect` if the proxy server is "auto detected" whatever that may mean.
 - `lpszAutoConfigUrl` a string with the url of the auto detect
 - `lpszProxy` the actual proxy url. Need to parse that to feed it into `CURLOPT_PROXY`, `CURLOPT_PROXYPORT`.
 - `lpszProxyBypass` a semicolon separated list of urls that you want to bypass. Need to parse and feed to `CURLOPT_NOPROXY`.

Libcurl also allows for setting `CURLOPT_PROXYTYPE`, `CURLOPT_PROXYUSERNAME`, `CURLOPT_PROXYPASSWORD`and `CURLOPT_PROXYAUTH` for which there is no windows equivalent I think.

**Comment by jmcphers** [comment]
Judging from a cursory reading of the SO post linked by @jeroenooms, auto-detected proxies require a further call to `WinHttpGetProxyForUrl` to get the actual proxy prior to handling a request, which I'm guessing is not possible by setting `CURLOPT_`.

IMO, it'd be reasonable to do the following:
- if no proxy config info is available (i.e. `WinHttpGetIEProxyConfigForCurrentUser` returns false), don't set any `CURLOPT_` automatically
- if a proxy is specified explicitly, use it if `CURLOPT_PROXY` is not set
- if the configuration specifies that an auto-detected proxy is to be used, look up the proxy URL per request if `CURLOPT_PROXY` is not set -- might need to get put behind an argument or flag; some systems may have the "autodetect" flag ticked but no actual proxy requirements, and I'm not sure what the behavior is there

**Comment by jeroenooms** [comment]
I don't have enough faith in this to enable it by default. For example I noticed if the configured proxy is set to an invalid or dead server, windows will silently ignore it. I suppose this is considered a feature. However if we set an invalid proxy in libcurl, it won't connect or might even crash.

Perhaps we can have something like `setInternet2` where the user can globally opt-in to automatically using the proxy.

**Comment by jeroenooms** [comment]
The 'auto proxy' just points to a piece of JavaScript that maps a URL to a proxy server: https://en.wikipedia.org/wiki/Proxy_auto-config

**Comment by jeroenooms** [comment]
This is now mostly implemented, see the [announcement post](https://www.opencpu.org/posts/curl-release-0-9-2/). However I do not have access to a proxy server to actually test this.

**Comment by sebastian-c** [comment]
I don't know if this is relevant but in the [latest R release (3.2.2)](https://stat.ethz.ch/pipermail/r-announce/2015/000589.html):

>  * (Windows only) setInternet2(TRUE) is now the default.  The
      command-line option --internet2 and environment variable
      R_WIN_INTERNET2 are now ignored.

**Comment by sonicrick** [comment]
Not working on my PAC. `ie_get_proxy_for_url(url)` threw an error `Error in ie_get_proxy_for_url(url) : ERROR_WINHTTP_UNABLE_TO_DOWNLOAD_SCRIPT`

`ie_proxy_info()$AutoConfigUrl` returns the PAC name e.g. http://myproxypac.mydomain/proxy.pac

**Comment by jeroenooms** [comment]
Can you show us the source code of your pac file?

**Comment by sonicrick** [comment]
A shortened and half-cleaned one here. Too long to clean all the IPs so I've omitted quite a few, I hope it doesn't affect the trouble shooting.

[proxypac.txt](https://github.com/jeroenooms/curl/files/32683/proxypac.txt)

**Comment by jeroenooms** [comment]
Mmm strange. In the topic you said initially that for `ie_get_proxy_for_url()` returned `"proxy.<my.domain>:8080"`. Did you change any settings?

**Comment by jeroenooms** [comment]
Can you test if any of these variations work?

```r
.Call(curl:::R_get_proxy_for_url, "http://www.google.com", T, "http://myproxypac.mydomain/proxy.pac")
.Call(curl:::R_get_proxy_for_url, "http://www.google.com", F, "http://myproxypac.mydomain/proxy.pac")
.Call(curl:::R_get_proxy_for_url, "http://www.google.com", T, NULL)
.Call(curl:::R_get_proxy_for_url, "http://www.google.com", F, NULL)
```

**Comment by sonicrick** [comment]
Apologies, apparently the error is my side (malformed value in `url`) causing the error. Your answer in SO worked for my `pac`, thanks!

Should I delete the question above since this is a false alarm? Or if you're still interested I can provide the responses for the four variations above.

**Comment by jeroenooms** [comment]
I think this is all working now. At least haven't heard complaints for a while.

**Comment by sagar-m** [comment]
Hi,

I'm rying to get bypass the pac proxy setup at my work to be able to download packages in R. The following gave me an error. Please advise! Greatly appreciate it.

Have attach a snapshot of my internet settings.


require("curl")

curl_with_proxy <- function(url, verbose = TRUE){
  proxy <- ie_get_proxy_for_url(url)
  h <- new_handle(verbose = verbose, proxy = proxy)
  curl(url, handle = h)
}

con <- curl_with_proxy("https://httpbin.org/get")
readLines(con)

Sys.setenv(http_proxy_user = "plum:apple")
Sys.setenv(http_proxy = "FGProxy1:3128")

The error that was printed in the console:

* No valid port number in proxy string (3128;FGProxy1:3128)
* timeout on name lookup is not supported
*   Trying 10.0.4.41...
* TCP_NODELAY set
* connect to 10.0.4.41 port 443 failed: Connection refused
* Failed to connect to FGProxy1 port 443: Connection refused
* Closing connection 0
Error in readLines(con) : Couldn't connect to server


![snip](https://cloud.githubusercontent.com/assets/27808289/25224913/75ca0e66-25dd-11e7-9100-774f1696fbcd.PNG)

**Comment by cderv** [comment]
with `download.file` and `method = "libcurl"`, it it explained that we could use `http_proxy` environment variable with the form `[user:password@]machine[:port]`. and it is working.

Is their a specificity in `curl` package that prevent from using this ? It does not seems to work.

**Comment by jeroen** [comment]
Curl uses separate varaibles for http and https proxy. rtm.

**Comment by cderv** [comment]
ok. So we should configure specifically for curl usage as `httr` does. 
I came here to find this issue because, I did not manage to configure curl to work with proxy when used in `jsonlite`. (even with `httr` function `use_proxy`)
Will try again, and differently. I will come back here to tell you if I manage to make it work.

**Comment by sagar-m** [comment]
Hi @cderv , not sure I followed. Please explain how I can resolve the error. Thank you so much.

**Comment by cderv** [comment]
As shown in the gist, configure environnement variables in R. It will be understand by libcurl. You just need to know you proxy url. `curl::ie_get_proxy_for_url()` could help.

```r
Sys.setenv(http_proxy = "[scheme://][user:password@]machine[:port]")
Sys.setenv(HTTPS_PROXY= "[scheme://][user:password@]machine[:port]")
```
Replace bracket parts with your specific case. for me, `[scheme://]` is `http://`

Try configure your proxy and run these lines to test

```r
# http test
readLines(base::url("http://httpbin.org/get", method = "libcurl"))
readLines(curl::curl("http://httpbin.org/get"))

# https test
readLines(base::url("https://httpbin.org/get", method = "libcurl"))
readLines(curl::curl("https://httpbin.org/get"))
```

**Comment by sagar-m** [comment]
Hi Jeroen,

Thank yoy for your suggestion; however I am still not able to get past
the proxy. Any comments would be much appreciated. Thank you very
much.

Your suggestion was:

Sys.setenv(http_proxy = "[scheme://][user:password@]machine[:port]")
Sys.setenv(HTTPS_PROXY= "[scheme://][user:password@]machine[:port]")

I altered it to:

Sys.setenv(http_proxy = "http://user:password@FGProxy1:3128")
Sys.setenv(HTTPS_PROXY = "http://user:password@FGProxy1:3128")

However, I am still not able to download packages.

The following command results in:

readLines(base::url("http://httpbin.org/get", method = "libcurl"))
readLines(curl::curl("http://httpbin.org/get"))

results in:

> readLines(base::url("http://httpbin.org/get", method = "libcurl"))
 [1] "{"
 [2] "  \"args\": {}, "
 [3] "  \"headers\": {"
 [4] "    \"Accept\": \"*/*\", "
 [5] "    \"Connection\": \"close\", "
 [6] "    \"Host\": \"httpbin.org\", "
 [7] "    \"User-Agent\": \"R (3.3.3 x86_64-w64-mingw32 x86_64 mingw32)\", "
 [8] "    \"X-Imforwards\": \"20\""
 [9] "  }, "
[10] "  \"origin\": \"203.215.51.245\", "
[11] "  \"url\": \"http://httpbin.org/get\""
[12] "}"
> readLines(curl::curl("http://httpbin.org/get"))
 [1] "{"
 [2] "  \"args\": {}, "
 [3] "  \"headers\": {"
 [4] "    \"Accept\": \"*/*\", "
 [5] "    \"Accept-Encoding\": \"gzip, deflate\", "
 [6] "    \"Connection\": \"close\", "
 [7] "    \"Host\": \"httpbin.org\", "
 [8] "    \"User-Agent\": \"r/curl/jeroen\", "
 [9] "    \"X-Imforwards\": \"20\""
[10] "  }, "
[11] "  \"origin\": \"203.215.51.245\", "
[12] "  \"url\": \"http://httpbin.org/get\""
[13] "}"

**Comment by jeroen** [comment]
@sagar-m from your output it looks like things are working. What error do you get?

**Comment by sagar-m** [comment]
Hi Jeroen,

When I code "install.packages("uroot"),

this is what I get:

> install.packages("uroot")
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES.gz': HTTP
status was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES': HTTP
status was '407 Proxy Authentication Required'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib
:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  cannot open URL '
http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.gz': HTTP status
was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES':
HTTP status was '407 Proxy Authentication Required'
Warning in install.packages :
  unable to access index for repository
http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Installing package into ‘C:/Users/362969/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES.gz': HTTP
status was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES': HTTP
status was '407 Proxy Authentication Required'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib
:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  cannot open URL '
http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.gz': HTTP status
was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES':
HTTP status was '407 Proxy Authentication Required'
Warning in install.packages :
  unable to access index for repository
http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘uroot’ is not available (for R version 3.3.3)
Warning in install.packages :
  closing unused connection 4 (http://httpbin.org/get)
Warning in install.packages :
  closing unused connection 3 (http://httpbin.org/get)
Warning in install.packages :
  cannot open URL '
https://cran.rstudio.com/bin/windows/contrib/3.3/PACKAGES.gz': HTTP status
was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/PACKAGES':
HTTP status was '407 Proxy Authentication Required'
Warning in install.packages :
  unable to access index for repository
https://cran.rstudio.com/bin/windows/contrib/3.3:
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/PACKAGES
'
Warning in install.packages :
  cannot open URL '
http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.3/PACKAGES.gz':
HTTP status was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL '
http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.3/PACKAGES': HTTP
status was '407 Proxy Authentication Required'
Warning in install.packages :
  unable to access index for repository
http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.3:
  cannot open URL '
http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.3/PACKAGES'

**Comment by jeroen** [comment]
You are using an old version of R. You can solve the problem by upgrading to R 3.4. If you don't want to upgrade, try this:


```r
install.packages("uroot", method = "libcurl")
```

**Comment by sagar-m** [comment]
Thank you so much. It is working now.

install.packages("txtplot", method = "libcurl") helped.
