### ISSUE TITLE
curl over TOR

### ISSUE THREAD

**Issue by jangorecki** [jeroenooms/curl#11]
Any way to add easy switch for using curl over the TOR network?
in shell you can run curl over tor easily:
```sh
sudo apt-get install tor
curl icanhazip.com
usewithtor curl icanhazip # some warnings on the way but the different ip achieved
```
or any particular place in the code where I would need to look at?

**Comment by jeroenooms** [comment]
The `usewithtor` program has nothing to do with curl.
