### ISSUE TITLE
handle_setopt() that takes list

### ISSUE THREAD

**Issue by hadley** [jeroenooms/curl#13]
Would be useful to have variant of `handle_setopt()` that lets you pass in a list of options

**Comment by jeroenooms** [comment]
It does support multiple options already. You mean something that would basically do: `do.call(handle_setopt, list(...))` ?

**Comment by hadley** [comment]
Yeah, exactly

**Comment by jeroenooms** [comment]
Okay makes sense. Prefer a separate function or overloading `curl_setopt`?

**Comment by hadley** [comment]
Similarly for `handle_setform()`. 

I quite like the `handle_setopt(x, ..., .list)` form

**Comment by hadley** [comment]
I wonder if it would also be possible to have a convention for calling `setform` from within the options list?

```R
opts <- list(setform = list(a = 1, b = form_file("abc.txt"))
handle_setopts(h, .list = opts)
```

What do you think? It would make my life easier to have a unified interface, but it's not a big deal.

**Comment by jeroenooms** [comment]
I don't feel strongly about it, the `handle_setopt(x, ..., .list)` form is fine. The only thing is that it is ambiguous what has to happen when an argument appears both in `...` and `.list`.

**Comment by hadley** [comment]
I think the last argument should always win:

```R
handle_setopt(x = 1, x = 2) # x = 2
handle_setopt(x = 1, .list = list(x = 2)) # x = 2
handle_setopt(.list = list(x = 1, x = 2)) # x = 2
```

etc
