### ISSUE TITLE
How best to expose symbols

### ISSUE THREAD

**Issue by jeroenooms** [jeroenooms/curl#16]
Curl has hundreds of C symbols that identify option names or possible values for options names.  The tricky part is that the available symbols depend on the version of libcurl. The libcurl author has included a plain-text table that lists which symbols were introduced or deprecated in which version. This [script](https://github.com/jeroenooms/curl/blob/master/tools/symbols.R) converts this table into a dataframe and looks up the actual integer value behind each symbol so we can set it at runtime.

Currently the table is not symbol exported: `curl:::curl_symbols`. I am not sure if this should be exported, or if we should only test internally in the curl if a symbol is available.

**Comment by hadley** [comment]
I'd find this useful as a quick lookup - I think it's reasonable to export it, but not in the documentation that it's not authorative, so don't rely on it too much.
