### ISSUE TITLE
Need curl_stream() or similar

### ISSUE THREAD

**Issue by hadley** [jeroenooms/curl#18]
Which returns same information as `curl_perform()`, plus a connection to listen to

**Comment by hadley** [comment]
It would be useful to some how make explicit that there are three things you can do with a curl request:

* load it in to memory
* save it to disk
* stream into a connection

And these are all just wrappers around the `writefunction` option.

**Comment by hadley** [comment]
How about `curl_download()`, `curl_fetch()` and `curl_stream()` which all return the same thing - a list of metadata about the request including a content field which contains either a path to a file, a raw vector, a connection?

**Comment by hadley** [comment]
Alternatively, could have `curl_perform(..., output = c("file", "memory", "connection"))` and then use an output field.

**Comment by hadley** [comment]
@jeroenooms I'm happy to implement this, but I want to make sure you're ok with the API first

**Comment by jeroenooms** [comment]
There are some additional differences. The `curl_download` and curl` functions automatically throw an error for a non-200 http response (to be compatible with `download.file` and `url`). You'd like to change that?

**Comment by hadley** [comment]
I think we'd leave the existing functions as is to keep that behaviour and add additional arguments to `curl_perform()`. I'll have a go at an implementation
