### ISSUE TITLE
Equivalent to RCurl::base64

### ISSUE THREAD

**Issue by hadley** [jeroenooms/curl#20]
What would you recommend?

**Comment by jeroenooms** [comment]
I think we can use the one from libssl. libcurl already depends on libssl so we don't need to link any additional libraries. An alternative would be simon's base64enc package, but It would be really nice to keep the package zero-dependency.

**Comment by jeroenooms** [comment]
What exactly do you need base64 for? There is also an argument for not providing this as part of `curl` and let the user or httr use base64enc to supply base64 data.

**Comment by hadley** [comment]
I need it for generate OAuth2 tokens - I don't mind if curl doesn't provide it.  A few other packages do have it, but I don't know which one is best

**Comment by jeroenooms** [comment]
I think simon's `base64enc` is the best.

**Comment by hadley** [comment]
Ok, I'll use that in httr.

**Comment by jeroenooms** [comment]
FYI I also added one to the openssl package, in case for whatever reason `base64enc` is not working out: https://github.com/jeroenooms/openssl/commit/6b37f405f53c938f7f1b7a869e8ef91e23c5238c
