### ISSUE TITLE
SSL validation

### ISSUE THREAD

**Issue by hadley** [jeroenooms/curl#21]
Why do you turn it off by default? It seems like a really really bad idea.

**Comment by jeroenooms** [comment]
Yes you're right. When I started working on the package I didn't want to hassle too much with certificates so I decided to just use opt-in rather than opt-out for validation. Starting version 3.2.0, R ships with a certificate bundle on windows so that makes it easier as well.

**Comment by hadley** [comment]
Maybe we should include the same cert bundle that httr does?

**Comment by jeroenooms** [comment]
Or we can just keep the `curl` package very minimal and let high-level package such as `httr` opt-in to validation using a supplied bundle.

**Comment by jeroenooms** [comment]
This won't work on windows. If we enable validation by default we need to ship a bundle and set `CURLOPT_SSLCERT` `CURLOPT_SSLCERTTYPE` `CURLOPT_SSL_OPTIONS` etc.

**Comment by jeroenooms** [comment]
It now does this:

 - On osx/linux, keep default settings and bundle.
 - On windows:
   * if `CURL_CA_BUNDLE` is set use this bundle.
   * else use the bundle included with R ( >= 3.2.0)
   * if neither is available then disable ssl validation and show a warning.
