### ISSUE TITLE
Support function callbacks

### ISSUE THREAD

**Issue by hadley** [jeroenooms/curl#22]
I use them in three places:

* To upload a file as request body (`readfunction`)
* To display a nicer progress bar (`progressfunction`)
* To display a nicer verbose output (`debugfunction`)

**Comment by hadley** [comment]
I'm reasonably certain I can implement these myself (following the template in RCurl), but I think you had some concerns about adding them to the API.

**Comment by jeroenooms** [comment]
We can easily add them, it's just find it a bit ugly to call R from C, so if there is an alternative I would prefer that. Do you need the `readfunction` only POST file contents? there should be a way to do that without callbacks.
