### ISSUE TITLE
Should we use curl_easy_perform?

### ISSUE THREAD

**Issue by hadley** [jeroenooms/curl#25]
It either succeeds or fails - if there's a long time out for some reason (e.g. `curl::curl_fetch_memory("http://httpbin.org/delay/10")`) , there's no way to interrupt the transfer.  Maybe we should instead use `curl_multi_perform`, regularly checking for interrupts?  

This problem only occurs before the server responds with headers or body, since we're already checking for interrupts in those places.

**Comment by jeroenooms** [comment]
Multi handles bring a lot of additional complexity. If it's just for interrupting, maybe we can use any of the callback handles? See http://curl.haxx.se/mail/lib-2010-09/0258.html

**Comment by jeroenooms** [comment]
I found that the easiest way for dealing with this is calling `R_CheckUserInterrupt();` inside `R_curl_callback_progress`. Why did you switch it to `pending_interrupt()` again?

**Comment by jeroenooms** [comment]
Ah I see the problem now, `R_CheckUserInterrupt` will leak because it skips over `free(body.buf);`

**Comment by jeroenooms** [comment]
In version 0.9.6 the `curl_fetch_memory` and `curl_fetch_disk` functions are not using `curl_easy_perform` anymore but a custom non-blocking replacement [`curl_perform_with_interrupt`](https://github.com/jeroenooms/curl/blob/v0.9.6/src/interrupt.c). This should be able to catch interruptions during any phase of the connection process.

There seems to be a little performance overhead but I can't figure out where it is coming from. Hopefully no other side effects.
