### ISSUE TITLE
Segmentation fault when calling handle_ functions with improper values

### ISSUE THREAD

**Issue by dkesh** [jeroenooms/curl#31]
The following functions result in segmentation faults:

```
curl::handle_setform(list(dummy=1))
curl::handle_setopt(list(dummy=1))
curl::handle_cookies(list(dummy=1))
```

I discovered this because I was getting a new error in curl::handle_setopt: "Unknown option: http.version", and in the process I forgot to feed handle_setopt the handle.  I do not expect the code to work, but do expect it to error more gracefully.

**Comment by jeroenooms** [comment]
Thanks. Fixed @ https://github.com/jeroenooms/curl/commit/409ca59f9c243e8aa38c91f521cefa75a926e5ba.
