### ISSUE TITLE
Installing on shared cluster

### ISSUE THREAD

**Issue by rushgeo** [jeroenooms/curl#36]
Our shared cluster uses environment modules to install most programs and shared libraries to a non-standard location, and add them to the path as needed. I can tell the package configuration where curl.h is by setting the CURL_INCLUDES environment variable (in my case =/sw/curl/include), but the install eventually fails:

```
gcc -std=gnu99 -shared -L/sw/R-3.2.1/lib -L/usr/local/lib64 -o curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o -lcurl -L/sw/R-3.2.1/lib -lR
/sw/binutils-2.25/bin/ld: cannot find -lcurl
collect2: ld returned 1 exit status
make: *** [curl.so] Error 1
ERROR: compilation failed for package ‘curl’
```

**Comment by jeroenooms** [comment]
What OS is this? Can you just symlink `libcurl.so` in a place where R can find it, such as `/usr/local/lib`? What do you get for:

```
pkg-config --libs libcurl
```

**Comment by jeroenooms** [comment]
Also try setting the `LDFLAGS` variable to where your `libcurl.so` is.

**Comment by rushgeo** [comment]
Thanks for the ideas. This is on CentOS 6.6. 

Here's how I have the environment module file set up currently:
```
set             approot                 /sw/curl

prepend-path    PATH                    $approot/bin
prepend-path    PKG_CONFIG_PATH         $approot
prepend-path    LDFLAGS                 $approot/lib
prepend-path    CURL_INCLUDES           $approot/include
```
Checking pkg-config:
```
$ pkg-config --libs libcurl
-L/sw/curl/lib -lcurl
```
Latest install attempt after adding LDFLAGS to the modulefile:
```
gcc -std=gnu99 -shared -L/sw/R-3.2.1/lib -L/usr/local/lib64 -o curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o /sw/curl/lib -lcurl -L/sw/R-3.2.1/lib -lR
/sw/curl/lib: file not recognized: Is a directory
collect2: ld returned 1 exit status
make: *** [curl.so] Error 1
```

**Comment by jeroenooms** [comment]
You need to set `LDFLAGS=-L/sw/curl/lib` (so include the `-L` part)

**Comment by rushgeo** [comment]
Ah, of course. Works perfectly now. Thanks!

**Comment by jeroenooms** [comment]
I refactored the configure script. Could you help me test if it now picks up on the flags automatically (or if you still have to set things manually)?
