### ISSUE TITLE
Quick fix for homebrew (OS X) users

### ISSUE THREAD

**Issue by jlisic** [jeroenooms/curl#38]
I thought I would just pass you a note for homebrew/OSX users.  In homebrew the curl headers are not put in any default search path to avoid conflicts with any system curl (unfortunately OS X does not ship with any headers for curl :disappointed: ).

So you might want to consider just adding an else if to search the homebrew location, 

`elif [ -r /usr/local/opt/curl/include/curl/curl.h ]; then
  CURL_INCLUDES="/usr/local/opt/curl/include"`

Anyway, thanks for the package.  If you want I could always make a pull request, but I probably won't get to that until Sunday night (EST).

**Comment by jeroenooms** [comment]
I'm quite sure osx does ship headers for curl. You should be able to build this package without brew (the cran build servers do so as well).

**Comment by jlisic** [comment]
Thanks, the issue seemed to be with Xcode being installed but not the command line tools.  Clang etc... and most of the essential bits are provided by Xcode, but /usr/include with curl etc... are provided by the command line tools.
