### ISSUE TITLE
curl package new version creating “msvcr80.dll” missing warning message

### ISSUE THREAD

**Issue by nayanj** [jeroenooms/curl#39]
I am currently using R version 3.2.1, and when I updated the "curl" package to version 0.9.2, I started getting following message after I run script that uses curl package (there is no such message with scripts that don't use curl):

"100% downloaded: rsession.exe-System Error"
The program can't start because MSVC80.dll is missing from your computer.
 Try installing the program to fix this problem.

There are OK and cross (as in multiplication sign) options. If I chose one of them, program continues without any error. It's, however, annoying that I get this message whenever I run the script that uses functions from curl package.

The description file of curl package has following:

Version:    0.9.2
Depends:    R (≥ 2.10.0)

But, on the closer look, I see this: "package ‘curl’ was built under R version 3.2.2". So, is this saying that I have to install new version of R (3.2.2) to run without any warning message? What if I don't want to update R version (now), but I do want to use new version of "curl" package (0.9.2)?

Note, that I have tried both with baseR and RStudio. Both gives the warning message when running scripts that use "curl" package. I would appreciate if you could take a closer look into this issue. I am using Windows 8.

**Comment by jeroenooms** [comment]
Does this happen both in 32 and 64 bit windows? Can you try installing the package from source?

**Comment by nayanj** [comment]
Thanks for the response. I am using 64 bit Windows ( I don't have an access to 32 bit windows). I tried installing the package from source using: `install.packages("https://cran.r-project.org/src/contrib/curl_0.9.2.tar.gz", repos = NULL, type="source"`,  but it still gives the same message. So, the problem still exists.

**Comment by jeroenooms** [comment]
The R installer for windows also includes a 32 bit R. Can you try it on that one? Can can you also test if the same problem appears on R 3.2.2? On Windows you can have multiple R installations so it won't affect your R 3.2.1 installation.

**Comment by nayanj** [comment]
I installed 32 bit R (3.2.1), and it doesn't generate message. I also installed both 32 bit and 64 bit R 3.2.2. As in 3.2.1, the message occurs only in 64 bit but not in 32 bit.

**Comment by jeroenooms** [comment]
This is very strange, I cannot reproduce this and have not heard anyone else about this. Can you show me the output of:

```r
install.packages("https://cran.r-project.org/src/contrib/curl_0.9.2.tar.gz", repos = NULL, type="source")
```

**Comment by nayanj** [comment]
Ok. Then, I guess it may be specific to my computer. The output is really large (see below). In the meantime, I will be sticking with 0.9.0 version, which is working so far. 

Installing package into ‘C:/Users/myuser/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/src/contrib/curl_0.9.2.tar.gz'
Content type 'application/x-gzip' length 244688 bytes (238 KB)
downloaded 238 KB

* installing *source* package 'curl' ...
** package 'curl' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
rm -f callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o curl.dll
"C:/PROGRA~1/R/R-32~1.2/bin/i386/Rscript.exe" "../tools/winlibs.R"
Warning message:
In download.file("https://github.com/rwinlib/libcurl/archive/v7.43.0.zip",  :
 downloaded length 5365533 != reported length 200
grep "^\W*CINIT(" "../windows/libcurl-7.43.0/include/curl/curl.h" > option_table.h
dlltool -k --output-lib libwinhttp.a --def winhttp32.def
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c callbacks.c -o callbacks.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c curl.c -o curl.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c download.c -o download.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c escape.c -o escape.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c fetch.c -o fetch.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c form.c -o form.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c getdate.c -o getdate.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c handle.c -o handle.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c ieproxy.c -o ieproxy.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c options.c -o options.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c utils.c -o utils.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c version.c -o version.o
gcc -m32 -shared -s -static-libgcc -o curl.dll tmp.def callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o -L../windows/libcurl-7.43.0/lib/i386 -L. -lwinhttp -lcurl -lssl -lcrypto -lssh2 -lrtmp -lidn -lintl -liconv -lgdi32 -lcrypt32 -lz -lws2_32 -lcrypt32 -lwldap32 -lwinmm -Ld:/RCompile/r-compiling/local/local320/lib/i386 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/PROGRA~1/R/R-32~1.2/bin/i386 -lR
installing to C:/Users/myuser/Documents/R/win-library/3.2/curl/libs/i386

*** arch - x64
rm -f callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o curl.dll
"C:/PROGRA~1/R/R-32~1.2/bin/x64/Rscript.exe" "../tools/winlibs.R"
grep "^\W*CINIT(" "../windows/libcurl-7.43.0/include/curl/curl.h" > option_table.h
dlltool -m i386:x86-64 --as-flags --64 --output-lib libwinhttp.a --def winhttp64.def
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c callbacks.c -o callbacks.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c curl.c -o curl.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c download.c -o download.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c escape.c -o escape.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c fetch.c -o fetch.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c form.c -o form.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c getdate.c -o getdate.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c handle.c -o handle.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c ieproxy.c -o ieproxy.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c options.c -o options.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c utils.c -o utils.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c version.c -o version.o
gcc -m64 -shared -s -static-libgcc -o curl.dll tmp.def callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o -L../windows/libcurl-7.43.0/lib/x64 -L. -lwinhttp -lcurl -lssl -lcrypto -lssh2 -lrtmp -lidn -lintl -liconv -lgdi32 -lcrypt32 -lz -lws2_32 -lcrypt32 -lwldap32 -lwinmm -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/PROGRA~1/R/R-32~1.2/bin/x64 -lR
installing to C:/Users/myuser/Documents/R/win-library/3.2/curl/libs/x64
Warning in file.copy(files, dest, overwrite = TRUE) :
 problem copying .\curl.dll to C:\Users\myuser\Documents\R\win-library\3.2\curl\libs\x64\curl.dll: Permission denied
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (curl)`

**Comment by jeroenooms** [comment]
Okay it says:

```
Warning in file.copy(files, dest, overwrite = TRUE) :
problem copying .\curl.dll to C:\Users\myuser\Documents\R\win-library\3.2\curl\libs\x64\curl.dll: Permission denied
```

This means the package could not be installed because it is currently in use. Can you restart R and run installation again (without loading the package first):

```
install.packages("https://cran.r-project.org/src/contrib/curl_0.9.2.tar.gz", repos = NULL, type="source")
```

**Comment by nayanj** [comment]
Thanks. Following is the output after removing the previous version and installing new version: The problem is still not resolved. 

Installing package into ‘C:/Users/nayan/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.r-project.org/src/contrib/curl_0.9.2.tar.gz'
Content type 'application/x-gzip' length 244688 bytes (238 KB)
downloaded 238 KB

* installing *source* package 'curl' ...
** package 'curl' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
rm -f callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o curl.dll
"C:/PROGRA~1/R/R-32~1.2/bin/i386/Rscript.exe" "../tools/winlibs.R"
Warning message:
In download.file("https://github.com/rwinlib/libcurl/archive/v7.43.0.zip",  :
  downloaded length 5365533 != reported length 200
grep "^\W*CINIT(" "../windows/libcurl-7.43.0/include/curl/curl.h" > option_table.h
dlltool -k --output-lib libwinhttp.a --def winhttp32.def
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c callbacks.c -o callbacks.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c curl.c -o curl.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c download.c -o download.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c escape.c -o escape.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c fetch.c -o fetch.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c form.c -o form.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c getdate.c -o getdate.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c handle.c -o handle.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c ieproxy.c -o ieproxy.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c options.c -o options.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c utils.c -o utils.o
gcc -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O3 -Wall  -std=gnu99 -mtune=core2 -c version.c -o version.o
gcc -m32 -shared -s -static-libgcc -o curl.dll tmp.def callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o -L../windows/libcurl-7.43.0/lib/i386 -L. -lwinhttp -lcurl -lssl -lcrypto -lssh2 -lrtmp -lidn -lintl -liconv -lgdi32 -lcrypt32 -lz -lws2_32 -lcrypt32 -lwldap32 -lwinmm -Ld:/RCompile/r-compiling/local/local320/lib/i386 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/PROGRA~1/R/R-32~1.2/bin/i386 -lR
installing to C:/Users/nayan/Documents/R/win-library/3.2/curl/libs/i386

*** arch - x64
rm -f callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o curl.dll
"C:/PROGRA~1/R/R-32~1.2/bin/x64/Rscript.exe" "../tools/winlibs.R"
grep "^\W*CINIT(" "../windows/libcurl-7.43.0/include/curl/curl.h" > option_table.h
dlltool -m i386:x86-64 --as-flags --64 --output-lib libwinhttp.a --def winhttp64.def
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c callbacks.c -o callbacks.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c curl.c -o curl.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c download.c -o download.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c escape.c -o escape.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c fetch.c -o fetch.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c form.c -o form.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c getdate.c -o getdate.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c handle.c -o handle.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c ieproxy.c -o ieproxy.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c options.c -o options.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c utils.c -o utils.o
gcc -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -I../windows/libcurl-7.43.0/include    -I"d:/RCompile/r-compiling/local/local320/include"  -DCURL_STATICLIB   -O2 -Wall  -std=gnu99 -mtune=core2 -c version.c -o version.o
gcc -m64 -shared -s -static-libgcc -o curl.dll tmp.def callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o options.o utils.o version.o -L../windows/libcurl-7.43.0/lib/x64 -L. -lwinhttp -lcurl -lssl -lcrypto -lssh2 -lrtmp -lidn -lintl -liconv -lgdi32 -lcrypt32 -lz -lws2_32 -lcrypt32 -lwldap32 -lwinmm -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/PROGRA~1/R/R-32~1.2/bin/x64 -lR
installing to C:/Users/nayan/Documents/R/win-library/3.2/curl/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (curl)

**Comment by jeroenooms** [comment]
Can you try installing [http://www.microsoft.com/en-us/download/details.aspx?id=21254](http://www.microsoft.com/en-us/download/details.aspx?id=21254)?

**Comment by nayanj** [comment]
Thank you. It is already installed in my computer. I have 2005, 2008, 2010, and 2013 versions.

**Comment by jeroenooms** [comment]
I can't reproduce this problem on any machine. So unless other people start reporting the same problems, I suspect something is wrong with your windows installation.

**Comment by nayanj** [comment]
Thank you for taking a look at the problem.

**Comment by jeroenooms** [comment]
Noone else has complained about this. I think it is a setup issue on your windows machine.
