### ISSUE TITLE
passing multiple form fields

### ISSUE THREAD

**Issue by soodoku** [jeroenooms/curl#46]
Dear Jeroen,

I am using curl for https://github.com/soodoku/clarifai

I am trying to pass multiple urls to the API, like so:
curl -H "Authorization: Bearer <access_token>" --data-urlencode "url=http://www.clarifai.com/img/metro-north.jpg" --data-urlencode "url=http://www.clarifai.com/img/metro-north.jpg"  https://api.clarifai.com/v1/tag/

I can do that with: 
handle_setform(h, url = "url1", url="url2")

But the number of urls being uploaded depends on user input. I am having trouble with building that.
I know I can't do: c("url = string1, url = string2") etc. There may be a do.call version of this but haven't found a way forward.

Any suggestions? Thanks.

**Comment by jeroenooms** [comment]
You can use the `.list` argument in `handle_setform` to pass the fields as a list instead of separate arguments.

**Comment by soodoku** [comment]
Dear Jeroen,

I tried: 
.list <- list(url="http://www.clarifai.com/img/metro-north.jpg", url="http://www.clarifai.com/img/metro-north.jpg")
    
    h <- new_handle()
	handle_setopt(h,  customrequest = "POST")
	handle_setheaders(h, "Authorization" = paste0("Bearer ", Sys.getenv("ClarifaiToken")))
	handle_setform(h, .list)

It yields: Error in handle_setform(h, .list) : 
  Insupported value type for form field ''.

I am sure I am doing something stupid. I would be grateful for your help.

**Comment by jeroenooms** [comment]
This seems to work:

```r
library(curl)
args <- list(test = "foo", test = "bar")
h <- new_handle(customrequest = "POST")
handle_setform(h, .list = args)
req <- curl_fetch_memory("http://httpbin.org/post", h)
cat(rawToChar(req$content))
```

**Comment by soodoku** [comment]
Astonishingly, it works for me too! 

Not sure what I was doing wrong. I spent like an hour yesterday trying to pass a list etc. 

Thanks for this.

Much appreciated.
