### ISSUE TITLE
best practice re: closing the connection?

### ISSUE THREAD

**Issue by jennybc** [jeroenooms/curl#48]
I am using `curl()` following usage I see in the official examples, like so:

``` r
x <- readLines(curl(SOME_URL)
```

but inside a loop over `SOME_URL`. I then got lots of warnings about closing unused connections. Am I supposed to be more careful and always store then close the connection? Does it even matter?

``` r
con <- curl(SOME_URL)
x <- readLines(con)
close(con)
```

**Comment by jeroenooms** [comment]
It doesn't really matter, but it is good practice to `close()` the connection. If you forget to, the garbage collector closes the connection when it cleans up the `con` object (with a warning). This holds for all connection types by the way (`url()`, `file()`, `socket()` etc), not just `curl()`. 

Within a function, it is common to use the `on.exit` finalizer for housekeeping. The benefit of  `on.exit` is that it also runs if the function exits with an error for whatever reason. 

```r
do_something <- function(SOME_URL){
  con <- curl(SOME_URL, open = "r")
  on.exit(close(con))
  readLines(con)
}
```

**Comment by jennybc** [comment]
Thanks that is helpful. Yes I had already decided to properly close the connections because the sheer volume of warnings was alarming. Good tip re: `on.exit()`.
