### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle)

### ISSUE THREAD

**Issue by BkrmDahal** [jeroenooms/curl#49]
i get this error when i try to run gs_key function from googlesheets packages
temp= gs_key(ggdoc_2)
Authentication will be used.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
How to slove it?

**Comment by jeroenooms** [comment]
Probably an issue with your internet connection. If it keeps happening you should open an issue at https://github.com/jennybc/googlesheets

**Comment by BkrmDahal** [comment]
Thanx jeroenooms.. some one messed up with our server...
