### ISSUE TITLE
Error while loading curl

### ISSUE THREAD

**Issue by kkaisurya** [jeroenooms/curl#50]
I have the latest version of curl(0.9.4) and each time I am trying to load the library. It throws the following:

Error in .loadNamespaceImpl(package, path, keep.source, partial): error executing useDynLib for dynamic library 'curl' from package 'curl' loaded from C:/abc/xyz/library: 
Error in library.dynam(chname = chname, package = package, lib.loc = ...: Foreign binary curl could not be loaded

Any idea on what could be causing it?

**Comment by jeroenooms** [comment]
I've never seen this. Can you provide more info on your system please. Which operating system do you use, any non-standard setup? Does the same thing happen when the package is installed in the default directory instead? Did you install it from source or the binary from CRAN?

**Comment by kkaisurya** [comment]
Sure. I am using in a visualization tool called Spotfire. There is an additional R Console which runs off from R 3.1.1.2 libraries. I installed it using install.packages('curl'). 
When installed in the default directory, there are no issues. I tried copying that library onto to the Spotfire library structure as well. That also did not work.

**Comment by jeroenooms** [comment]
I don't think this issue is related to `curl` but rather the way Spotfire manages R packages. Are you not getting the same problem for other packages with compiled code? One thing you could try is compile from source: 

```r
library(devtools)
install_github("jeroenooms/curl", lib = "C:/abc/xyz/library")
```

**Comment by kkaisurya** [comment]
Sure.. While doing that, probably found out what the issue was. Firstly, I was not able to call the library(devtools) from the Spotfire console. The reason is the 'Namespace' file has useDynLib(). Same is the case for 'Curl' 's 'Namespace' file as well. So not sure, what I should use instead of 'useDynLib()' :(

**Comment by jeroenooms** [comment]
Can you try this instead:

```
install.packages("curl", type = "source", lib = "C:/abc/xyz/library")
```
