### ISSUE TITLE
/bin/bash invalid on OpenBSD

### ISSUE THREAD

**Issue by feinerer** [jeroenooms/curl#56]
On OpenBSD bash is installed (it is not available in the base system) at /usr/local/bin/, so https://github.com/jeroenooms/curl/blob/master/configure#L1 fails.

If you do not want to use /bin/sh, another solution would be "/usr/bin/env bash".

However, using bash at all is considered bad style: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Writing-portable-packages states "Bash extensions also need to be avoided in shell scripts". So /bin/sh would be the best solution.

**Comment by jeroenooms** [comment]
Thanks for these suggestions. Can you help me figure out if the standard shell in OpenBSD supports:

 - `$(cmd)` instead of backticks?
 - The [command](http://pubs.opengroup.org/onlinepubs/009696699/utilities/command.html) utility?

I.e. if we remove the shebang, does the configure script just work in OpenBSD?

**Comment by feinerer** [comment]
Yes, both `$(cmd)` and `command` are supported (see http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/ksh.1?query=ksh for details).

With the shebang removed the configure scripts works fine if I revert your latest commit "Better method to detect static linking" (as it uses =~ which does not seem to be supported).

**Comment by jeroenooms** [comment]
Thank you. I have made some changes to try and make the configure script more portable. Can you test if you can install the package now?

**Comment by feinerer** [comment]
Yes, it works now. Thanks a lot!

**Comment by jeroenooms** [comment]
Could you do me a favor and test if you can install the openssl package open OpenBSD https://github.com/jeroenooms/openssl

**Comment by jeroenooms** [comment]
FYI this is on cran now, so you should be able to do `install.packages("curl")`
