### ISSUE TITLE
Issue installing on OS X El Capitan

### ISSUE THREAD

**Issue by steevmi1** [jeroenooms/curl#57]
I've got R and curl installed via MacPorts on OS X, and when I try to install curl (even after checking out the latest from github), it keeps failing at the very end of the install.
```
$ R CMD INSTALL .
WARNING: ignoring environment value of R_HOME
* installing to library ‘/Users/steevmi1/Library/R/3.2/library’
* installing *source* package ‘curl’ ...
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/opt/local/include
Using PKG_LIBS=-L/opt/local/lib -lcurl
** libs
make: Nothing to be done for `all'.
installing to /Users/steevmi1/Library/R/3.2/library/curl/libs
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Users/steevmi1/Library/R/3.2/library/curl/libs/curl.so':
  dlopen(/Users/steevmi1/Library/R/3.2/library/curl/libs/curl.so, 6): Symbol not found: _SSLv2_client_method
  Referenced from: /opt/local/lib/libcurl.4.dylib
  Expected in: /opt/local/lib/libssl.1.0.0.dylib
 in /opt/local/lib/libcurl.4.dylib
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/steevmi1/Library/R/3.2/library/curl’
* restoring previous ‘/Users/steevmi1/Library/R/3.2/library/curl’
```

**Comment by jeroenooms** [comment]
The problem is that you build with curl from macports, however R still uses the system version of libcurl that comes with osx: `/usr/lib/libcurl.dylib`. Easiest solution is uninstall curl from macports and build against the osx one.

**Comment by steevmi1** [comment]
I did a bit more testing this morning. It actually looks like the issue is with the prebuilt binary that macports pulls down. If I reinstall curl and force a build from source then everything seems to build fine. Unfortunately, the git package (among others) requires curl from macports so uninstalling and relying on the system one wasn't really an option.

Thanks for checking into this, though.
