### ISSUE TITLE
Curl not working with IPv6 on Windows

### ISSUE THREAD

**Issue by cgaylord** [jeroenooms/curl#59]
I have a web service that has some clients with IPv6-only connectivity that need to use httr (and hence curl). On Mac we have had this work well, but we're were surprised to find on Windows it fails.

The error message is "unable to resolve host". While we ultimately expect DNS with AAAA record to be used, testing with IP is a good step:

con= curl(url="http://[2001:468:c80:a202:0:b074:0:c082]/~cgaylord/x.txt")
readLines(con)

gives "cannot resolve host [2001"

(I will leave that file there for a while so others can test.)

Results otherwise are variable, but we have had success with Mac at least.

My thought is: is this a deficiency of a statically linked libcurl that does not have proper IPv6 functionality? I'm happy to drop another library in, if there's a suggestion of how best to do this.

Thanks!

**Comment by cgaylord** [comment]
Hostname for the example is funnel.vtti.vt.edu if you want to test your DNS resolution too.

**Comment by cgaylord** [comment]
The readme for libcurl 7.43 within this package does indicate it is built with --enable-ipv6

**Comment by cgaylord** [comment]
read.table("http://...") gives mixed results; apparently there is some variability there as well. However, on at least some Windows hosts I can test with, I have successfully used read.table where curl fails as described above.

**Comment by jeroenooms** [comment]
Afaik, ipv6 support depends on the operating system. Which windows are you testing on? Can you verify that this problem exists on Windows 10 or Windows server 2008?

**Comment by cgaylord** [comment]
The systems being used are Windows 7, which otherwise has had excellent
IPv6 compatibility. I have not found a Server 2008 box or Windows 10 near
me that has R installed.

On Thu, Apr 7, 2016 at 1:36 PM, Jeroen Ooms <notifications@github.com>
wrote:

> Afaik, ipv6 support depends on the operating system. Which windows are you
> testing on? Can you verify that this problem exists on Windows 10 or
> Windows server 2008?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jeroenooms/curl/issues/59#issuecomment-207017950>
>



-- 
Clark Gaylord
clark.gaylord@gmail.com

**Comment by cgaylord** [comment]
Btw read.table("http....") works fine to IPv6 host on the same client.

**Comment by cgaylord** [comment]
> library(curl)
> curl::nslookup("funnel.vtti.vt.edu")
[1] "2001:468:c80:a202:0:b074:0:c082"

> con=curl("http://funnel.vtti.vt.edu/~cgaylord/x.txt")
> readLines(con)
[1] "42"
  --- netstat indicates this is using legacy IP

> con=curl("http://[2001:468:c80:a202:0:b074:0:c082]/~cgaylord/x.txt")
> readLines(con)
Error in readLines(con) : Couldn't resolve host name

> read.table("http://funnel.vtti.vt.edu/~cgaylord/x.txt")
  V1
1 42
   --- netstat indicates this is using IPv6

> read.table("http://[2001:468:c80:a202:0:b074:0:c082]/~cgaylord/x.txt")
  V1
1 42

**Comment by cgaylord** [comment]
> curl::nslookup("ipv6.test-ipv6.com")
[1] "2001:470:1:18::119"

**Comment by cgaylord** [comment]
On Mac:
> con=curl("http://[2001:468:c80:a202::b074:0:c082]/~cgaylord/x.txt")
> readLines(con)
[1] "42"

Although, ironically Mac read.table is broken:
> read.table("http://[2001:468:c80:a202::b074:0:c082/~cgaylord/x.txt")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") : unable to resolve '[2001'

**Comment by jeroenooms** [comment]
I think it is actually a bug in libcurl. Updating libcurl for Windows seems to fix the problem. Can you try to install the new curl:

```
install.packages("https://github.com/jeroenooms/curl/archive/master.tar.gz", repos = NULL)
```

**Comment by cgaylord** [comment]
That seems to have done it -- thanks!

> con=curl(url="http://[2001:468:c80:a202::b074:0:c082]/~cgaylord/x.txt")
> readLines(con)
[1] "42"

**Comment by jeroenooms** [comment]
OK I pushed this update to CRAN so it should be available in a day or so.
