### ISSUE TITLE
Configure script does not confirm curl was compiled with libz support

### ISSUE THREAD

**Issue by gmbecker** [jeroenooms/curl#60]
When pointed at a libcurl compiled without libz support enabled, the package will install succesfully, but segfault when collecting version info here https://github.com/jeroenooms/curl/blob/master/src/version.c#L12 because the libz_version field of the struct is NULL.

If libz support is mandatory then the package configuration script should fail if the libcurl it finds doesn't have it.

**Comment by jeroenooms** [comment]
Hmmm thanks for catching this. I would have guessed that `mkString(NULL)` returns `NA` but I guess it doesn't.

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/curl/commit/0f6e4b164f019f1bb3deabc1a2508a7d04813ed1.
