### ISSUE TITLE
Possible to POST an object from memory?

### ISSUE THREAD

**Issue by leeper** [jeroenooms/curl#62]
I am wondering whether it is possible to POST an object from memory (e.g., a raw vector representation of a file)? The use case here is performing a file upload without having to write the object to disk first.

**Comment by jeroenooms** [comment]
Maybe this is easier with `httr`:

```r
mydata <- serialize(iris, NULL)
req <- httr::POST("http://httpbin.org/post", body = mydata)

# Verify that the payload was indeed posted
payload <- jsonlite::fromJSON(httr::content(req, "text"))
b64 <- sub("data:application/octet-stream;base64,", "", payload$data)
unserialize(openssl:::base64_decode(b64))

```

**Comment by leeper** [comment]
That looks perfect, actually. Thanks!
