### ISSUE TITLE
nslookup.c:30:32: error: dereferencing pointer to incomplete type

### ISSUE THREAD

**Issue by tlevine** [jeroenooms/curl#64]
curl fails to install for me with the following error.

```
> install.packages('curl')
...
gcc48 -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG -I/usr/local/include -I/usr/local/include -DLIBICONV_PLUG    -fpic  -O2 -pipe  -fno-builtin-coshl -fno-builtin-erfcl -fno-builtin-erfl -fno-builtin-lgammal -fno-builtin-powl -fno-builtin-sinhl -fno-builtin-tanhl -fno-builtin-tgammal -DLIBICONV_PLUG -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing  -c init.c -o init.o
gcc48 -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG -I/usr/local/include -I/usr/local/include -DLIBICONV_PLUG    -fpic  -O2 -pipe  -fno-builtin-coshl -fno-builtin-erfcl -fno-builtin-erfl -fno-builtin-lgammal -fno-builtin-powl -fno-builtin-sinhl -fno-builtin-tanhl -fno-builtin-tgammal -DLIBICONV_PLUG -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing  -c interrupt.c -o interrupt.o
gcc48 -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG -I/usr/local/include -I/usr/local/include -DLIBICONV_PLUG    -fpic  -O2 -pipe  -fno-builtin-coshl -fno-builtin-erfcl -fno-builtin-erfl -fno-builtin-lgammal -fno-builtin-powl -fno-builtin-sinhl -fno-builtin-tanhl -fno-builtin-tgammal -DLIBICONV_PLUG -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing  -c nslookup.c -o nslookup.o
nslookup.c: In function 'R_nslookup':
nslookup.c:27:31: error: dereferencing pointer to incomplete type
     inet_ntop(AF_INET, &(sa_in->sin_addr), ip, INET_ADDRSTRLEN);
                               ^
nslookup.c:30:32: error: dereferencing pointer to incomplete type
     inet_ntop(AF_INET6, &(sa_in->sin6_addr), ip, INET6_ADDRSTRLEN);
                                ^
*** Error code 1

Stop.
make: stopped in /tmp/RtmpTpEdQ7/R.INSTALLa22b6a634b6d/curl/src
ERROR: compilation failed for package ‘curl’
* removing ‘/usr/home/tlevine/R/amd64-portbld-freebsd10.3-library/3.3/curl’

The downloaded source packages are in
        ‘/tmp/RtmpcCXt42/downloaded_packages’
Warning message:
In install.packages("curl") :
  installation of package ‘curl’ had non-zero exit status
```

I am on PC-BSD 10.3, running R 3.3.0.

    > uname -a
    FreeBSD x220 10.3-RELEASE-p1 FreeBSD 10.3-RELEASE-p1 #0: Thu May  5 14:48:00 UTC 2016     root@amd64-builder.pcbsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by tlevine** [comment]
That error was on the latest version in CRAN, but I just tried with the HEAD of master, and I get the same error.

**Comment by jeroenooms** [comment]
Strange, the [latest commit](https://github.com/jeroenooms/curl/commits/master/src/nslookup.c) to this file by @jasperla was to make it work on FreeBSD. I don't have a BSD system to debug this...

**Comment by jasperla** [comment]
@jeroenooms nope, it was meant to unbreak it on OpenBSD, not FreeBSD.
@tlevine  could you try adding an include for `netinet/in.h` ?

**Comment by tlevine** [comment]
Including netinet/in.h indeed helped. Below I provide two versions on
the code. I have installed both versions successfully on both FreeBSD
and Debian, so I don't know which version is better; I don't really know
anything about C or porting.

Both versions are available in this git repository.

    git://github.com/tlevine/curl

Commit a2ec991e4d08fdcd7828498249d8ba36b85450af adds just one line,
the new include.

		diff --git a/src/nslookup.c b/src/nslookup.c
		index b208cb9..1d8ddfe 100644
		--- a/src/nslookup.c
		+++ b/src/nslookup.c
		@@ -9,6 +9,7 @@ const char *inet_ntop(int af, const void *src, char *dst, socklen_t size);
		 #include <sys/socket.h>
		 #include <netdb.h>
		 #include <arpa/inet.h>
		+#include <netinet/in.h>
		 #endif
		 
		 SEXP R_nslookup(SEXP hostname) {

Commit cc1a766dd28a9f1ff8a0edcff5b88f03457820c3 includes the file only
on FreeBSD.

		diff --git a/src/nslookup.c b/src/nslookup.c
		index b208cb9..692a65f 100644
		--- a/src/nslookup.c
		+++ b/src/nslookup.c
		@@ -9,6 +9,9 @@ const char *inet_ntop(int af, const void *src, char *dst, socklen_t size);
		 #include <sys/socket.h>
		 #include <netdb.h>
		 #include <arpa/inet.h>
		+#ifdef __FreeBSD__
		+#include <netinet/in.h>
		+#endif
		 #endif
		 
		 SEXP R_nslookup(SEXP hostname) {

**Comment by jeroenooms** [comment]
OK I merged it, thanks. Would you mind testing if the `openssl` package works on FreeBSD?

**Comment by tlevine** [comment]
Thanks. The versions of openssl in both CRAN and in the HEAD of master
both look fine; I managed to install both, and all of the tests passed.
