### ISSUE TITLE
curl install failure /lib64/libgssapi_krb5.so.2

### ISSUE THREAD

**Issue by majaidi** [jeroenooms/curl#67]
I have a problem installing the curl package and get the following error on all versions.

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/majaidi/R/x86_64-redhat-linux-gnu-library/3.1/curl/libs/curl.so':
  /lib64/libgssapi_krb5.so.2: symbol krb5int_buf_len, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
Error: loading failed

Have you come across this issue before?

**Comment by jeroenooms** [comment]
Please provide information on your platform and version of libcurl and how you installed libcurl.

**Comment by majaidi** [comment]
THe platform has the following:

Kernel: 2.6.32-431.1.2.el6.x86_64
Red Hat Enterprise Linux Server release 6.5 (Santiago)
R version 3.1.0

I have managed to go around it by using a hack but on the current machine it is still not installing.
I have tried installing all the versions and working backwards but still no success.
Have you come across this issue before? RCUrl also suffers from the same error

**Comment by jeroenooms** [comment]
It looks like you have a corrupted version of `libcurl` installed on your machine.

**Comment by majaidi** [comment]
Can you please develop?. 
libcurl has been installed using YUM I am surprised that this is a libcurl issue since it points to a Kerberos LIB.

**Comment by jeroenooms** [comment]
Can you please post your full installation log of installing the R package in curl?

**Comment by majaidi** [comment]
I 

Found pkg-config cflags and libs!
Using PKG_CFLAGS= 
Using PKG_LIBS=-lcurl  
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c callbacks.c -o callbacks.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c curl.c -o curl.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c download.c -o download.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c escape.c -o escape.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c fetch.c -o fetch.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c form.c -o form.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c getdate.c -o getdate.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c handle.c -o handle.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c ieproxy.c -o ieproxy.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c init.c -o init.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c interrupt.c -o interrupt.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c nslookup.c -o nslookup.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c utils.c -o utils.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I/usr/local/include    -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c version.c -o version.o
gcc -m64 -std=gnu99 -shared -L/usr/local/lib64 -o curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o nslookup.o utils.o version.o -lcurl -L/usr/lib64/R/lib -lR
  converting help for package \u2018curl\u2019
    curl                                    html  
    curl_download                           html  
    curl_escape                             html  
    curl_fetch                              html  
    curl_options                            html  
    form_file                               html  
    handle                                  html  
    handle_cookies                          html  
    ie_proxy                                html  
    nslookup                                html  
    parse_date                              html  
    parse_headers                           html  
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/j7774969/R/x86_64-redhat-linux-gnu-library/3.1/curl/libs/curl.so':
  /lib64/libgssapi_krb5.so.2: symbol krb5int_buf_len, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
Error: loading failed
Execution halted

**Comment by jeroenooms** [comment]
I think you have a conflict due to multiple versions of `libcurl` on your machine. Are you sure there is not a second copy of `libcurl` in `/usr/local` ?

You can debug the problem like this:

```sh
wget https://cran.r-project.org/src/contrib/curl_0.9.7.tar.gz
R CMD INSTALL curl_0.9.7.tar.gz --no-test-load
ldd /home/majaidi/R/x86_64-redhat-linux-gnu-library/3.1/curl/libs/curl.so
```

Then find the location of `libcurl.so` and use `ldd libcurl.so` to see what else it links to.

**Comment by majaidi** [comment]
THey both reference some Kerberos library one way or another

Here's the list for libcurl.so
	linux-vdso.so.1 =>  (0x00007fff25225000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007f836f32c000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f836f0df000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f836eed6000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f836ec92000)
	libkrb5.so.3 => /usr/local/nz/lib64/libkrb5.so.3 (0x00007f836eab2000)
	libk5crypto.so.3 => /usr/local/nz/lib64/libk5crypto.so.3 (0x00007f836e96e000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f836e76a000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f836e554000)
	libssl3.so => /usr/lib64/libssl3.so (0x00007f836e315000)
	libsmime3.so => /usr/lib64/libsmime3.so (0x00007f836e0e9000)
	libnss3.so => /usr/lib64/libnss3.so (0x00007f836ddab000)
	libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f836db7e000)
	libplds4.so => /lib64/libplds4.so (0x00007f836d97a000)
	libplc4.so => /lib64/libplc4.so (0x00007f836d775000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f836d537000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f836d31a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f836d116000)
	libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f836ceed000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f836cb59000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f836c94a000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f836c72f000)
	libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007f836c515000)
	/lib64/ld-linux-x86-64.so.2 (0x00000039ab800000)
	libkrb5support.so.0 => /usr/local/nz/lib64/libkrb5support.so.0 (0x00007f836c408000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f836c204000)
	libcom_err.so.3 => /usr/local/nz/lib64/libcom_err.so.3 (0x00007f836c101000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f836be94000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f836bab4000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f836b87d000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f836b605000)


Here's the list. For curl.so	

linux-vdso.so.1 =>  (0x00007fffc4dff000)
	libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f718efd9000)
	libR.so => /usr/lib64/R/lib/libR.so (0x00007f718ea15000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f718e680000)
	libidn.so.11 => /lib64/libidn.so.11 (0x00007f718e44e000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f718e201000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f718dff8000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f718ddb4000)
	libkrb5.so.3 => /usr/local/nz/lib64/libkrb5.so.3 (0x00007f718dbd4000)
	libk5crypto.so.3 => /usr/local/nz/lib64/libk5crypto.so.3 (0x00007f718da90000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f718d88c000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f718d676000)
	libssl3.so => /usr/lib64/libssl3.so (0x00007f718d437000)
	libsmime3.so => /usr/lib64/libsmime3.so (0x00007f718d20b000)
	libnss3.so => /usr/lib64/libnss3.so (0x00007f718cecd000)
	libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f718cca0000)
	libplds4.so => /lib64/libplds4.so (0x00007f718ca9c000)
	libplc4.so => /lib64/libplc4.so (0x00007f718c897000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f718c659000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f718c43c000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f718c238000)
	libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f718c00f000)
	libblas.so.3 => /usr/lib64/libblas.so.3 (0x00007f718bdb8000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f718bac6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f718b841000)
	libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f718b5fe000)
	libicuuc.so.42 => /usr/lib64/libicuuc.so.42 (0x00007f718b2ac000)
	libicui18n.so.42 => /usr/lib64/libicui18n.so.42 (0x00007f718af15000)
	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f718ad08000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f718aaf2000)
	/lib64/ld-linux-x86-64.so.2 (0x00000039ab800000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f718a8e2000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f718a6c8000)
	libsasl2.so.2 => /usr/lib64/libsasl2.so.2 (0x00007f718a4ae000)
	libkrb5support.so.0 => /usr/local/nz/lib64/libkrb5support.so.0 (0x00007f718a3a0000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f718a19d000)
	libcom_err.so.3 => /usr/local/nz/lib64/libcom_err.so.3 (0x00007f718a09a000)
	libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f7189e2d000)
	libcrypto.so.10 => /usr/lib64/libcrypto.so.10 (0x00007f7189a4d000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f718982b000)
	libicudata.so.42 => /usr/lib64/libicudata.so.42 (0x00007f71886e6000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f71883e0000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f71881a8000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f7187f31000)

**Comment by jeroenooms** [comment]
It looks like you have a version conflict for Kerberos. Whatever is in `/usr/local/nz/lib64/` was most likely not installed by yum, and it conflicts with your system libraries.

**Comment by majaidi** [comment]
Cool! I have done a LD_LIBRARY_PATH and that sorted the issue.
Thanks a lot for all the Help

**Comment by jeroenooms** [comment]
OK great.
