### ISSUE TITLE
Stream buffer size

### ISSUE THREAD

**Issue by gaborcsardi** [jeroenooms/curl#75]
It would be great to set the buffer size to something smaller to allow streaming output from remote processes.

**Comment by jeroenooms** [comment]
Which buffer exactly?

**Comment by gaborcsardi** [comment]
I don't know how it works internally, I just want my function to be called more frequently from `curl_fetch_stream()`. I know that the data is sent, but it is not printed, I guess because it is buffered.

**Comment by jeroenooms** [comment]
`curl_fetch_stream` is a simple wrapper around `curl::curl`. The buffer is set [here](https://github.com/jeroenooms/curl/blob/master/R/fetch.R#L89). Just write your own wrapper:

```r
mystream <- function(url, bufsize = 1024){
  con <- curl::curl(url)
  if(!isOpen(con)){
    open(con, "rb")
    on.exit(close(con))
  }
  while(length(buf <- readBin(con, raw(), bufsize))){
    callback(buf)
  }
}
```

**Comment by gaborcsardi** [comment]
Cool! Exactly what I need. Sorry for not looking to it more.
