### ISSUE TITLE
fail to build from source in windows without internet connections

### ISSUE THREAD

**Issue by shrektan** [jeroenooms/curl#78]
It seems like in windows, when building from source, `curl` needs to update the library `libcurl`, via https://github.com/jeroenooms/curl/blob/master/tools/winlibs.R#L4

`download.file("https://github.com/rwinlib/libcurl/archive/v7.50.3.zip", "lib.zip", quiet = TRUE)`

But, it ends up with being difficult to build from source without internet connections.

Is it desired behavior?

Thanks.

**Comment by shrektan** [comment]
It seems like `curl` is not the only package that needs external files. Packages like `stringi` also need internet connections to be able to build from sources...

**Comment by jeroenooms** [comment]
Yes this is expected, how do you install the R package in the first place without internet access?

You only have to download these libs once, after that you can (re) install the package offline.

**Comment by shrektan** [comment]
Sure I'll close this issue. 

But I though the CRAN packages were required to complied without internet access.

I'm actually using packrat to create a project so that it can be used on a special computer, that's strictly prohibited from the network connection. And I surprisingly find source files themselves are not enough...

Thanks anyway.

**Comment by jeroenooms** [comment]
That's the problem with windows, it doesn't have a package manager providing libraries such as `libcurl`. We are also not allowed to ship such binaries with the R source package. So we need an alternative method to pull in `libcurl` when building the source package.

However you should always be able to install the windows binary package offline?

**Comment by shrektan** [comment]
Yes, I tried and it's ok to install binary pkgs offline. Thanks for your explanations. Have a nice day. 😀
