### ISSUE TITLE
Inconsistent close(con) 

### ISSUE THREAD

**Issue by eddelbuettel** [jeroenooms/curl#8]
See [this file](https://github.com/eddelbuettel/random/blob/master/R/random.R) where I just switched to `curl::curl()` because the site switched from http to https and `url()` is no longer of use.

I can `close(con)` in the first routine following `readLines()`; in all the other ones following `read.table()` I get an error.  That seems odd.  Is this a bug?

**Comment by jeroenooms** [comment]
This is a feature of R connections, it has nothing to do with the `curl` implementation. You will get the same behavior for `url`. When you explicitly `close` a connection it gets destroyed and cannot be reused:

```s
con <- url("http://cran.r-project.org/CRAN_mirrors.csv")
close(con)
print(con)
```

And `?read.table` says:

> Alternatively, file can be a readable text-mode connection (which will be opened for reading if necessary, and if so closed (and hence destroyed) at the end of the function call)

So if will always destroy the connection once it is done. Now, `readLines` has a special feature that allows to open-read-close a connection without destroying it:

```s
con <- url("http://cran.r-project.org/CRAN_mirrors.csv")
readLines(con)
isOpen(con)
readLines(con)
isOpen(con)
```

So perhaps you could use in your code:

```s
read.table(text = readLines(con)) or something.
```

**Comment by eddelbuettel** [comment]
Ack.  I guess I was unaware of what is documented (!!) behaviour of `read.table()`.

/cc @hadley
