### ISSUE TITLE
Set curl options

### ISSUE THREAD

**Issue by nqbao** [jeroenooms/curl#87]
Is there a way i can set curl option? I see there is `curl_options` but i can't find anyway for me to set an option. For example in PHP, there is a [curl_setopt](http://php.net/manual/en/function.curl-setopt.php) that allow me to override the option. Can we support that in R curl package?

**Comment by jeroenooms** [comment]
Please read the manual page for `?handle_setopt` or the [intro vignette](https://cran.r-project.org/web/packages/curl/vignettes/intro.html).

**Comment by nqbao** [comment]
Got it! Thanks!!
