### ISSUE TITLE
Unknown option: unix_socket_path, libcurl 7.51.0, MacOS Sierra 

### ISSUE THREAD

**Issue by duxan** [jeroenooms/curl#89]
Hello,

I'm trying to connect to unix socket, which does work from CLI: `/usr/bin/curl --unix-socket /var/run/docker.sock http://localhost/images/json` with same libcurl version as used from R session (both `$> /usb/bin/curl --version` from CLI and `curl_version()` from R give **7.51.0**). If I  understood correctly, I should be able to set CURLOPT_UNIX_SOCKET_PATH like this:

```{r}
h <- new_handle()
handle_setopt(h, UNIX_SOCKET_PATH = "/var/run/docker.sock")
```

but instead I get `Unknown option: unix_socket_path`. And indeed it is not in curl_options(), even though from curl_symbols, it should be available for libcurl > 7.40.0:

```
curl_symbols[grepl("UNIX", curl_symbols$name),]
                         name introduced deprecated removed  value   type
137 CURL_VERSION_UNIX_SOCKETS     7.40.0       <NA>    <NA> 524288   <NA>
678  CURLOPT_UNIX_SOCKET_PATH     7.40.0       <NA>    <NA>  10231 string
```

What am I missing here? Is there a reason why this option is not supported yet?

Tnx!

**Comment by duxan** [comment]
@jeroenooms Sorry to bother you, but do you have any info on this issue?

**Comment by jeroenooms** [comment]
Can you try installing from source:

```r
install.packages("curl", type = "source")
```
And then see if it works:

```r
library(curl)
h <- new_handle()
handle_setopt(h, UNIX_SOCKET_PATH = "/var/run/docker.sock")```

**Comment by duxan** [comment]
It did work - I should've thought of trying that first. Tnx! Closing..

**Comment by jeroenooms** [comment]
OK great. For further reference: the problem is that CRAN builds package binaries on OSX 10.9 which has an older version of `libcurl` that is missing some recent features.
