### ISSUE TITLE
cannot install curl on mac sierra

### ISSUE THREAD

**Issue by rodmiga** [jeroenooms/curl#90]
Hello,

I'm trying to install curl on mac osx.  I get the error:

Error in source("tools/option_table.txt", env) : 
  tools/option_table.txt:1:1: unexpected input
1: 
   ^
Error : unable to load R code in package ‘curl’

Log is below.

Thanks.

install.packages("curl",dependencies=TRUE)
Installing package into ‘/usr/local/lib/R/3.3/site-library’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
HTTPS CRAN mirror 

 1: 0-Cloud [https]                 2: Algeria [https]              
 3: Australia (Canberra) [https]    4: Australia (Melbourne) [https]
 5: Australia (Perth) [https]       6: Austria [https]              
 7: Belgium (Ghent) [https]         8: Brazil (RJ) [https]          
 9: Brazil (SP 1) [https]          10: Bulgaria [https]             
11: Canada (MB) [https]            12: Chile 1 [https]              
13: Chile 2 [https]                14: China (Beijing) [https]      
15: China (Hefei) [https]          16: China (Lanzhou) [https]      
17: Colombia (Cali) [https]        18: Czech Republic [https]       
19: Denmark [https]                20: France (Lyon 1) [https]      
21: France (Lyon 2) [https]        22: France (Marseille) [https]   
23: France (Montpellier) [https]   24: France (Paris 2) [https]     
25: Germany (Falkenstein) [https]  26: Germany (Münster) [https]    
27: Iceland [https]                28: India [https]                
29: Ireland [https]                30: Italy (Padua) [https]        
31: Japan (Tokyo) [https]          32: Malaysia [https]             
33: Mexico (Mexico City) [https]   34: New Zealand [https]          
35: Norway [https]                 36: Philippines [https]          
37: Russia (Moscow) [https]        38: Serbia [https]               
39: Spain (A Coruña) [https]       40: Spain (Madrid) [https]       
41: Sweden [https]                 42: Switzerland [https]          
43: Taiwan (Chungli) [https]       44: Turkey (Denizli) [https]     
45: UK (Bristol) [https]           46: UK (Cambridge) [https]       
47: UK (London 1) [https]          48: USA (CA 1) [https]           
49: USA (IA) [https]               50: USA (IN) [https]             
51: USA (KS) [https]               52: USA (MI 1) [https]           
53: USA (TN) [https]               54: USA (TX) [https]             
55: (HTTP mirrors)                 

Selection: 25
trying URL 'https://mirrors.cicku.me/CRAN/src/contrib/curl_2.3.tar.gz'
Content type 'application/gzip' length 400460 bytes (391 KB)
==================================================
downloaded 391 KB

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
** libs
rm -f curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o utils.o version.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c callbacks.c -o callbacks.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c curl.c -o curl.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c download.c -o download.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c escape.c -o escape.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c fetch.c -o fetch.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c form.c -o form.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c getdate.c -o getdate.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c handle.c -o handle.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c ieproxy.c -o ieproxy.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c init.c -o init.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c interrupt.c -o interrupt.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c multi.c -o multi.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c nslookup.c -o nslookup.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c reflist.c -o reflist.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c utils.c -o utils.o
clang -I/usr/local/Cellar/r/3.3.2/R.framework/Resources/include -DNDEBUG  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2  -c version.c -o version.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/Cellar/r/3.3.2/R.framework/Resources/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o curl.so callbacks.o curl.o download.o escape.o fetch.o form.o getdate.o handle.o ieproxy.o init.o interrupt.o multi.o nslookup.o reflist.o utils.o version.o -lcurl -F/usr/local/Cellar/r/3.3.2/R.framework/.. -framework R -lintl -Wl,-framework -Wl,CoreFoundation
installing to /usr/local/lib/R/3.3/site-library/curl/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in source("tools/option_table.txt", env) : 
  tools/option_table.txt:1:1: unexpected input
1: 
   ^
Error : unable to load R code in package ‘curl’
ERROR: lazy loading failed for package ‘curl’
* removing ‘/usr/local/lib/R/3.3/site-library/curl’

The downloaded source packages are in
	‘/private/var/folders/9j/y_j2p025137bk39lhv5zgx3w0000gn/T/Rtmp7MJwlD/downloaded_packages’
Warning message:
In install.packages("curl", dependencies = TRUE) :
  installation of package ‘curl’ had non-zero exit status

**Comment by jeroenooms** [comment]
Do you have any custom console or `grep` setting? The configure script uses grep to extract symbols from the headers: https://github.com/jeroenooms/curl/blob/master/configure#L68

**Comment by rodmiga** [comment]
It was my grep customisations. Thank you so much!
