### ISSUE TITLE
[feature request] pretty-print curl_download progress bar

### ISSUE THREAD

**Issue by jsta** [jeroenooms/curl#91]
The progress bar returned by setting `quiet = FALSE`  in `curl_download` is very long and unwieldy. Is it possible to pretty-print this to a minimal number of columns?

>% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0 12.2M    0 13094    0     0   3799

**Comment by jeroenooms** [comment]
In the handle you can set a custom `progress_function`. See [here](https://github.com/hadley/httr/blob/master/R/progress.R) how httr does this.
