### ISSUE TITLE
Add non-binary file list option to make_form?

### ISSUE THREAD

**Issue by ampu3ro** [jeroenooms/curl#93]
This is more of a question than a request, as I may just be missing something...

I think it might be useful to be able to define the content-type for a non-binary element of a multipart form. Basically, I have [this issue](http://stackoverflow.com/questions/42356834/how-to-post-multipart-binary-non-binary-with-httr-for-salesforce-api) with binary & non-binary parts and I have a hunch that defining an intermediate case in `make_form` could do the trick:
```C
curl_formadd(&post, &last, CURLFORM_COPYNAME, name, CURLFORM_COPYCONTENTS, body, CURLFORM_CONTENTTYPE, content_type, CURLFORM_END);
```

The idea is that I could pass a string with a defined content-type (similar to the second example [here](https://curl.haxx.se/libcurl/c/curl_formadd.html#CURLFORMFILE)):
```S
url <- "https://my_salesforce_instance/services/data/v39.0/sobjects/Document/"
header <-  httr::add_headers("my_salesforce_auth")

x <- data.frame(FolderId="a0a1300000ZG7u3",Name="test1.png")
json <- jsonlite::toJSON(unbox(x),pretty=T)
doc <- list(body=json,content_type="application/json")

tmp <- tempfile(fileext=".png")
png(tmp)
plot(mtcars)
dev.off()
body <- httr::upload_file(tmp)

httr::POST(url,header,body=list(entity_document=doc,Body=body),encode="multipart",verbose())
```

I couldn't get a local build of `curl` with this tweak to work, but I'm not at all confident writing C code. On the other hand this may not even be relevant to solve the issue. Any suggestions?

**Comment by jeroenooms** [comment]
Did you read the [section on posting forms](https://cran.r-project.org/web/packages/curl/vignettes/intro.html#posting_forms) from the vignette? The `curl::form_file` function allows you to specify a content type. Perhaps you can use this?

**Comment by jeroenooms** [comment]
Hmm reading the SO, maybe I don't fully understand the question. Let me look into it better.

**Comment by ampu3ro** [comment]
Thanks for the quick reply. Yeah, I think what I'm describing is something between a simple character like `foo`, which is handled with 
```C
curl_formadd(&post, &last, CURLFORM_COPYNAME, name, CURLFORM_COPYCONTENTS, translateCharUTF8(asChar(val)), CURLFORM_END);
``` 
and a form file like `logo` which is handled with 
```C
curl_formadd(&post, &last, CURLFORM_COPYNAME, name, CURLFORM_FILE, path, CURLFORM_CONTENTTYPE, content_type, CURLFORM_END);
```
As mentioned above, I'm not even sure this will solve the problem so if you have any other ideas I'm open to them! Thanks

**Comment by jeroenooms** [comment]
I don't think there is a distinction between binary and non-binary data inside a multipart body. I think `--data-binary` simply means that you want to use multipart encoding.

Only multipart encoding supports setting a content type, from your example:

```
>> Content-Disposition: form-data; name="y"; filename="db_biggest_tables.csv"
>> Content-Type: application/octet-stream
```

If you post a `x-www-form-urlencoded` encoded body, then values simply get turned into a big `val=foo&val2=bar` string so there is no way to specify a content type. 

So I'm not sure what exactly it is that you want, but from your SO post it kind of looks like a bug on in the salesforge API?

**Comment by ampu3ro** [comment]
I guess, more to the point, I'm wondering if the multipart body could have a part with the header
```
>> Content-Disposition: form-data; name="entity_document"
>> Content-Type: application/json
```
This doesn't seem possible with `curl` because I can only get
```
>> Content-Disposition: form-data; name="entity_document"; filename="file1510059b5200f"
>> Content-Type: application/json
```
if I use `form_file` (technically `httr::upload_file`) or
```
>> Content-Disposition: form-data; name="entity_document"
```
if I `POST` the json/character directly.

It's certainly possible that Salesforce API has a bug, it just seems unlikely to me given how many organizations use it and how this operation is documented.

**Comment by jeroenooms** [comment]
OK I get it now. You want to set a `Content-Type` but **not** a `filename` value?

**Comment by ampu3ro** [comment]
Yep! Sorry that wasn't very clear before. Do you think that might solve the issue? It's the only obvious mismatch I can see between Salesforce's example and mine. I can also imagine that functionality would be useful more generally, but I don't know enough about Curl to have a good sense.

**Comment by jeroenooms** [comment]
OK I have added a new function `form_data` which allows you to post a string or raw vector with a custom content type. Can you give this a try? To install the dev version of curl in a clean R session:

```r
install.packages("https://github.com/jeroenooms/curl/archive/master.tar.gz", repos = NULL)
```

And then look at `?form_data`

**Comment by ampu3ro** [comment]
Beautiful! Worked like a charm. I really appreciate the help and speed in execution

**Comment by ampu3ro** [comment]
Just closing the loop, `httr::body_config` will need updating in order work with this enhancement. Happy to post an issue on that repo tomorrow. Thanks again!
